import type { StorySpec } from "../UsmileStory";

import spec0 from "./usmile-c10-01-floss-vs-water.json";
import spec1 from "./usmile-c10-02-braces-food-trap.json";
import spec2 from "./usmile-c10-03-corn-test.json";
import spec3 from "./usmile-c10-04-take-it-anywhere.json";
import spec4 from "./usmile-p10-01-how-it-works.json";
import spec5 from "./usmile-p10-02-skeleton-morning.json";
import spec6 from "./usmile-p10-03-roman-warrior.json";
import spec7 from "./usmile-p10-04-gym-bag.json";

/** Generated by projects/_ads/tools/usmile_story.py — do not edit by hand. */
export const SPECS: StorySpec[] = [spec0 as StorySpec, spec1 as StorySpec, spec2 as StorySpec, spec3 as StorySpec, spec4 as StorySpec, spec5 as StorySpec, spec6 as StorySpec, spec7 as StorySpec];
