import type { StorySpec } from "../UsmileStory";

import spec0 from "./usmile-c10-01-floss-vs-water.json";
import spec1 from "./usmile-c10-02-braces-food-trap.json";
import spec2 from "./usmile-p10-01-how-it-works.json";
import spec3 from "./usmile-p10-02-skeleton-morning.json";

/** Generated by projects/_ads/tools/usmile_story.py — do not edit by hand. */
export const SPECS: StorySpec[] = [spec0 as StorySpec, spec1 as StorySpec, spec2 as StorySpec, spec3 as StorySpec];
