/**
 * "ตำนานยักษ์กับจิ้งจก" ตอนที่ 2 — ทุ่งน้ำผึ้งมรณะ.
 *
 * The old gecko explains his missing tail: the young giant's glue traps
 * ("the field of honey"), the tail he left wriggling on one to get free, the
 * clutch of eggs swept into the bin, and the tribe's answer — black rain and
 * a warning call on the morning the giant goes to meet his new boss. It ends
 * on the long box with the air rifle and the torch.
 *
 * Every shot is a Kling 2.5 clip whose first frame is the still in `src`.
 * Generated by projects/gecko-legend/ep02/build_ep2.py — edit there.
 */

import type { Caption, Episode, Shot } from "../roachwar/constants";

const DIR = "geckolegend/ep02";
const clip = (n: string) => `${DIR}/video/${n}.mp4`;
const still = (n: string) => `${DIR}/${n}.png`;

const shot = (
  id: string,
  n: string,
  from: number,
  to: number,
  extra: Partial<Shot> = {},
): Shot => ({
  id,
  src: still(n),
  video: clip(n),
  durationInSeconds: Number((to - from).toFixed(3)),
  zoom: [1.0, 1.0],
  ...extra,
});

const SHOTS: Shot[] = [
  shot("the-tail-stump", "s01", 0.0, 7.16),
  shot("the-ladder", "s02", 7.16, 13.9),
  shot("honey-field", "s03", 13.9, 17.25),
  shot("hungry-nights", "s04", 17.25, 20.33),
  shot("the-first-moth", "s05", 20.33, 29.84),
  shot("hang-dam-forbids", "s06", 29.84, 34.58),
  shot("young-and-hungry", "s07", 34.58, 37.24),
  shot("stuck", "s08", 37.24, 41.93),
  shot("three-others", "s09", 41.93, 47.31),
  shot("let-it-go", "s10", 47.31, 54.61),
  shot("the-tail", "s11", 54.61, 57.42),
  shot("it-wriggles-till-dawn", "s12", 57.42, 60.36),
  shot("the-cleaning", "s13", 60.36, 63.94),
  shot("behind-the-cabinet", "s14", 63.94, 66.99),
  shot("he-counted-them", "s15", 66.99, 69.0),
  shot("into-the-bin", "s16", 69.0, 73.44),
  shot("the-empty-corner", "s17", 73.44, 76.87),
  shot("the-tribe-rises", "s18", 76.87, 79.29),
  shot("black-rain", "s19", 79.29, 84.95),
  shot("the-white-shirt", "s20", 84.95, 93.55),
  shot("tak", "s21", 93.55, 97.67),
  shot("she-would-stop", "s22", 97.67, 100.16, { video: "geckolegend/ep01/video/s09.mp4", src: "geckolegend/ep01/s09.png" }),
  shot("he-laughs", "s23", 100.16, 102.5),
  shot("the-drop", "s24", 102.5, 109.03),
  shot("he-comes-home", "s25", 109.03, 113.25),
  shot("the-long-box", "s26", 113.25, 120.96),
  shot("the-beam", "s27", 120.96, 125.96),
];

const CAPTIONS: Caption[] = [
  { text: "ลูกหลานมักถามข้า", from: 0.0, to: 1.38 },
  { text: "ว่าหางของข้าหายไปไหน", from: 1.33, to: 3.29 },
  { text: "ข้าทิ้งมันไว้ที่ทุ่งน้ำผึ้งมรณะ", from: 3.24, to: 5.16 },
  { text: "และมันช่วยชีวิตข้าไว้", from: 5.11, to: 7.16 },
  { text: "เช้าวันนั้น", from: 7.21, to: 8.15 },
  { text: "ยักษ์ปีนขึ้นมาใกล้ฟ้าของเรา", from: 8.1, to: 10.31 },
  { text: "วางแผ่นสีเหลืองไว้ตามขอบผนัง", from: 10.26, to: 12.35 },
  { text: "ข้างดวงอาทิตย์ที่ดับไปแล้ว", from: 12.3, to: 14.0 },
  { text: "ต้องแสงเช้า", from: 13.95, to: 14.91 },
  { text: "มันเป็นประกายเหมือนทุ่งน้ำผึ้ง", from: 14.86, to: 17.16 },
  { text: "ตั้งแต่ดวงอาทิตย์ดับ", from: 17.3, to: 18.68 },
  { text: "เผ่าของเราหิวมาหลายคืน", from: 18.63, to: 20.43 },
  { text: "พอค่ำลง", from: 20.38, to: 21.54 },
  { text: "แมลงตัวแรกก็บินมาติดอยู่บนแผ่นนั้น", from: 21.49, to: 23.86 },
  { text: "แล้วตัวที่สอง ตัวที่สาม", from: 23.81, to: 25.62 },
  { text: "ดิ้นอยู่ตรงหน้าเรา", from: 25.57, to: 27.02 },
  { text: "เหมือนอาหารที่ใครวางไว้ให้", from: 26.97, to: 29.83 },
  { text: "หางดำห้ามทุกคน", from: 29.89, to: 31.46 },
  { text: "เขาบอกว่าของที่ยักษ์วางไว้ให้", from: 31.41, to: 33.63 },
  { text: "ไม่เคยให้ฟรี", from: 33.58, to: 34.68 },
  { text: "แต่ข้ายังหนุ่ม", from: 34.63, to: 35.71 },
  { text: "และข้าหิว", from: 35.66, to: 37.12 },
  { text: "ข้าก้าวลงไปแค่ปลายเท้า", from: 37.29, to: 39.09 },
  { text: "มันก็ไม่ยอมปล่อย", from: 39.04, to: 40.23 },
  { text: "ยิ่งดิ้น ตัวก็ยิ่งจม", from: 40.18, to: 42.03 },
  { text: "ข้างตัวข้ามีพวกเราอีกสามตน", from: 41.98, to: 44.04 },
  { text: "ติดอยู่ตั้งแต่หัวค่ำ", from: 43.99, to: 45.24 },
  { text: "ตนหนึ่งเลิกดิ้นไปแล้ว", from: 45.19, to: 47.11 },
  { text: "หางดำปีนลงมาหาข้า", from: 47.36, to: 49.28 },
  { text: "เขาไม่ได้ดุ", from: 49.23, to: 50.14 },
  { text: "เขาบอกแค่ว่า ทิ้งมันซะ", from: 50.09, to: 52.09 },
  { text: "พวกเราเกิดมาพร้อมของที่ทิ้งได้หนึ่งอย่าง", from: 52.04, to: 54.71 },
  { text: "ข้าหลับตา", from: 54.66, to: 55.52 },
  { text: "แล้วปล่อยหางของข้าไว้บนนั้น", from: 55.47, to: 57.52 },
  { text: "มันยังดิ้นอยู่แทนข้าจนรุ่งเช้า", from: 57.47, to: 60.11 },
  { text: "ภรรยาของยักษ์ใกล้คลอดแล้ว", from: 60.41, to: 62.14 },
  { text: "เช้านั้นเขาจึงล้างบ้านทั้งหลัง", from: 62.09, to: 64.04 },
  { text: "หลังตู้ในครัว", from: 63.99, to: 65.26 },
  { text: "เขาเจอไข่ของเราสิบกว่าฟอง", from: 65.21, to: 67.09 },
  { text: "ไข่ที่หางดำไปนั่งนับทุกคืน", from: 67.04, to: 69.1 },
  { text: "ยักษ์ปัดมันลงถังพร้อมแผ่นเหลือง", from: 69.05, to: 71.32 },
  { text: "ไข่เหล่านั้นไม่เคยได้ฟัก", from: 71.27, to: 73.24 },
  { text: "คืนนั้น", from: 73.49, to: 74.27 },
  { text: "หางดำนั่งอยู่หน้าตู้ที่ว่างเปล่าจนสว่าง", from: 74.22, to: 76.97 },
  { text: "แล้วเผ่าของเราก็ขึ้นไปบนฟ้าพร้อมกัน", from: 76.92, to: 79.39 },
  { text: "ฝนดำตกลงบนจานข้าวของยักษ์", from: 79.34, to: 81.42 },
  { text: "บนหมอน บนแปรงสีฟัน", from: 81.37, to: 83.45 },
  { text: "ทุกคืน", from: 83.4, to: 84.65 },
  { text: "แล้ววันสำคัญของยักษ์ก็มาถึง", from: 85.0, to: 87.21 },
  { text: "เขาใส่เสื้อเชิ้ตขาวตัวดีที่สุด", from: 87.16, to: 89.16 },
  { text: "จะไปพบเจ้านายคนใหม่", from: 89.11, to: 90.77 },
  { text: "ภรรยาจัดคอเสื้อให้", from: 90.72, to: 92.24 },
  { text: "บอกว่าวันนี้ต้องได้", from: 92.19, to: 93.65 },
  { text: "พอเขาเอื้อมมือไปเปิดประตู", from: 93.6, to: 95.38 },
  { text: "เราร้องทักพร้อมกันทั้งเผ่า", from: 95.33, to: 97.57 },
  { text: "ถ้าเป็นยักษ์ชรา", from: 97.72, to: 98.93 },
  { text: "นางจะหยุดเดิน", from: 98.88, to: 100.26 },
  { text: "แต่ยักษ์ตนนี้หัวเราะ", from: 100.21, to: 101.44 },
  { text: "แล้วก้าวออกไป", from: 101.39, to: 102.6 },
  { text: "ฝนดำหยดหนึ่ง", from: 102.55, to: 103.55 },
  { text: "หล่นลงบนไหล่เสื้อขาวของเขาพอดี", from: 103.5, to: 105.68 },
  { text: "เขาต้องกลับเข้าไปเปลี่ยนเสื้อ", from: 105.63, to: 107.31 },
  { text: "และไปถึงช้ากว่าที่นัดไว้", from: 107.26, to: 109.13 },
  { text: "เย็นนั้น", from: 109.08, to: 109.81 },
  { text: "เขากลับมาโดยไม่พูดอะไรสักคำ", from: 109.76, to: 112.48 },
  { text: "คืนนั้น", from: 112.81, to: 113.35 },
  { text: "เขาเปิดกล่องยาวใบหนึ่ง", from: 113.3, to: 115.16 },
  { text: "ข้างในมีกระบอกสีดำ", from: 115.11, to: 116.85 },
  { text: "กับไฟฉายดวงเล็ก", from: 116.8, to: 117.76 },
  { text: "ที่สว่างกว่าดวงอาทิตย์ของยักษ์ชราเสียอีก", from: 117.71, to: 120.62 },
  { text: "ตอนต่อไป · สายฟ้าที่มองไม่เห็น", from: 121.76, to: 125.66 },
];

export const GECKO_LEGEND_EP02: Episode = {
  voiceoverSrc: `${DIR}/vo.mp3`,
  musicSrc: `${DIR}/music.mp3`,
  musicVolume: 0.22,
  shots: SHOTS,
  captions: CAPTIONS,
  timestampShots: [],
  timestampLabel: "",
  captionStyle: "legend",
  cleanLook: true,
};
