/**
 * "ตำนานยักษ์กับจิ้งจก" ตอนที่ 3 — สายฟ้าที่มองไม่เห็น.
 *
 * The giant hunts the ceiling at night with the torch and the air rifle.
 * The tailless narrator freezes in the beam; หางดำ runs through it to draw
 * the shot and dies, his tail still wriggling in the giant's hand. The
 * wife's labour starts in the quarrel that follows, the gun goes up on the
 * cabinet, and the tribe watches over the new baby — until something long
 * and red crawls out of the bathroom drain.
 *
 * Every shot is a Kling 2.5 clip whose first frame is the still in `src`.
 * Generated by projects/gecko-legend/ep03/build_ep3.py — edit there.
 */

import type { Caption, Episode, Shot } from "../roachwar/constants";

const DIR = "geckolegend/ep03";
const clip = (n: string) => `${DIR}/video/${n}.mp4`;
const still = (n: string) => `${DIR}/${n}.png`;

const shot = (
  id: string,
  n: string,
  from: number,
  to: number,
  extra: Partial<Shot> = {},
): Shot => ({
  id,
  src: still(n),
  video: clip(n),
  durationInSeconds: Number((to - from).toFixed(3)),
  zoom: [1.0, 1.0],
  ...extra,
});

const SHOTS: Shot[] = [
  shot("the-elder-remembers", "s01", 0.0, 3.33),
  shot("white-light", "s02", 3.33, 11.51),
  shot("the-hunter", "s03", 11.51, 16.54),
  shot("caught-in-the-light", "s04", 16.54, 20.21),
  shot("into-the-cracks", "s05", 20.21, 29.13),
  shot("no-tail", "s06", 29.13, 35.21),
  shot("i-cannot-run", "s06b", 35.21, 39.19),
  shot("the-light-finds-me", "s07", 39.19, 44.94),
  shot("he-laughs", "s08", 44.94, 47.54),
  shot("hang-dam-runs", "s09", 47.54, 53.7),
  shot("pop", "s10", 53.7, 57.05),
  shot("he-falls", "s11", 57.05, 60.88),
  shot("the-tail-in-his-hand", "s12", 60.88, 63.88),
  shot("like-mine", "s13", 63.88, 66.4),
  shot("she-cries", "s14", 66.4, 72.4),
  shot("the-sky-shakes", "s15", 72.4, 74.17),
  shot("she-falls", "s16", 74.17, 77.39),
  shot("into-the-night", "s17", 77.39, 80.86),
  shot("the-smallest-giant", "s18", 80.86, 85.24, { video: undefined, zoom: [1.0, 1.06] }),
  shot("the-gun-put-away", "s19", 85.24, 89.63),
  shot("the-cradle", "s20", 89.63, 95.39),
  shot("we-watch", "s21", 95.39, 100.27),
  shot("they-sleep", "s22", 100.27, 102.72),
  shot("the-drain", "s23", 102.72, 108.4),
  shot("toward-the-cradle", "s24", 108.4, 111.56),
  shot("hundred-legs", "s25", 111.56, 116.56),
];

const CAPTIONS: Caption[] = [
  { text: "ในเผ่าของเรา", from: 0.01, to: 1.3 },
  { text: "ไม่มีใครเคยเห็นสายฟ้าของยักษ์", from: 1.25, to: 3.43 },
  { text: "เราเห็นแค่แสงสีขาวกวาดไปบนฟ้า", from: 3.38, to: 5.95 },
  { text: "ได้ยินเสียงดังป๊อกเบาๆ", from: 5.9, to: 7.85 },
  { text: "แล้วใครสักคนก็ร่วงลงไป", from: 7.8, to: 9.58 },
  { text: "ไม่กลับขึ้นมาอีก", from: 9.53, to: 11.5 },
  { text: "ยักษ์ออกล่าทุกคืน", from: 11.56, to: 13.01 },
  { text: "เขาเดินช้าๆ ไปตามห้อง", from: 12.96, to: 14.57 },
  { text: "ส่องไฟขึ้นมาบนฟ้าของเรา", from: 14.52, to: 16.64 },
  { text: "ตนไหนหยุดนิ่งอยู่ในแสงนั้น", from: 16.59, to: 18.42 },
  { text: "ก็คือตนต่อไป", from: 18.37, to: 20.12 },
  { text: "คืนแรกเราเสียพี่น้องไปสองตน", from: 20.26, to: 22.32 },
  { text: "คืนที่สามอีกสี่", from: 22.27, to: 23.78 },
  { text: "หางดำสั่งให้ทุกคนหลบอยู่ในรอยแตกของฝ้า", from: 23.73, to: 26.65 },
  { text: "ห้ามออกมาจนกว่าแสงจะดับ", from: 26.6, to: 28.66 },
  { text: "ส่วนข้า", from: 28.69, to: 29.23 },
  { text: "ตั้งแต่ทิ้งหางไว้บนทุ่งน้ำผึ้ง", from: 29.18, to: 31.54 },
  { text: "ข้าก็วิ่งไม่เร็วเหมือนเดิม", from: 31.49, to: 32.98 },
  { text: "ปีนผนังทีไรก็เสียหลักทุกที", from: 32.93, to: 35.31 },
  { text: "ข้ารู้ดีว่าถ้าแสงนั้นมาถึงตัว", from: 35.26, to: 37.67 },
  { text: "ข้าหนีไม่พ้น", from: 37.62, to: 39.08 },
  { text: "แล้วคืนนั้นก็มาถึง", from: 39.24, to: 40.67 },
  { text: "แสงสีขาวหยุดอยู่ตรงหน้าข้าพอดี", from: 40.62, to: 43.15 },
  { text: "ข้าตัวแข็ง ขยับไม่ได้", from: 43.1, to: 45.04 },
  { text: "ได้ยินเสียงยักษ์หัวเราะอยู่ข้างล่าง", from: 44.99, to: 47.35 },
  { text: "หางดำกระโดดออกมาจากรอยแตก", from: 47.59, to: 49.94 },
  { text: "วิ่งตัดผ่านแสงนั้นไปอีกฝั่งของฟ้า", from: 49.89, to: 52.38 },
  { text: "แสงหันตามเขาไป", from: 52.33, to: 53.8 },
  { text: "แล้วเสียงป๊อกก็ดังขึ้น", from: 53.75, to: 55.54 },
  { text: "ครั้งเดียว", from: 55.49, to: 56.86 },
  { text: "หางดำร่วงลงไปบนพื้น", from: 57.1, to: 58.9 },
  { text: "ยักษ์หยิบเขาขึ้นมาด้วยปลายนิ้ว", from: 58.85, to: 60.98 },
  { text: "หางของเขายังดิ้นอยู่ในมือยักษ์", from: 60.93, to: 62.92 },
  { text: "เหมือนหางของข้า", from: 62.87, to: 63.98 },
  { text: "ที่เคยดิ้นอยู่บนทุ่งน้ำผึ้ง", from: 63.93, to: 66.22 },
  { text: "คืนนั้นภรรยาของยักษ์ร้องไห้", from: 66.45, to: 68.75 },
  { text: "นางตะโกนว่าบ้านที่กำลังจะมีเด็ก", from: 68.7, to: 71.22 },
  { text: "ไม่ควรมีปืน", from: 71.17, to: 72.5 },
  { text: "ยักษ์ตะโกนกลับจนฝ้าสั่น", from: 72.45, to: 74.27 },
  { text: "แล้วนางก็ทรุดลง", from: 74.22, to: 75.6 },
  { text: "กุมท้องไว้แน่น", from: 75.55, to: 77.11 },
  { text: "ยักษ์อุ้มนางวิ่งออกไปกลางดึก", from: 77.44, to: 79.16 },
  { text: "บ้านว่างเปล่าอยู่สามวัน", from: 79.11, to: 80.96 },
  { text: "พอกลับมา", from: 80.91, to: 81.65 },
  { text: "ในอ้อมแขนของนาง", from: 81.6, to: 83.12 },
  { text: "มียักษ์ตัวเล็กที่สุดที่เราเคยเห็น", from: 83.07, to: 85.34 },
  { text: "กระบอกสีดำถูกเก็บขึ้นไปไว้บนตู้", from: 85.29, to: 87.5 },
  { text: "ไม่มีใครแตะมันอีกเลย", from: 87.45, to: 89.53 },
  { text: "ยักษ์ตัวเล็กนอนอยู่ในเปลใต้ฟ้าของเรา", from: 89.68, to: 92.23 },
  { text: "ทุกคืนพวกเราลงมาอยู่บนผนัง", from: 92.18, to: 94.33 },
  { text: "ดูมันหายใจ", from: 94.28, to: 95.49 },
  { text: "ข้าไม่รู้ว่าทำไม", from: 95.44, to: 96.73 },
  { text: "แต่ไม่มีใครในเผ่า", from: 96.68, to: 98.06 },
  { text: "อยากให้มันเป็นอะไรไป", from: 98.01, to: 99.88 },
  { text: "จนคืนหนึ่ง", from: 100.32, to: 101.32 },
  { text: "ตอนที่ยักษ์ทั้งสองหลับสนิท", from: 101.27, to: 102.82 },
  { text: "มีบางอย่างคลานออกมาจากท่อในห้องน้ำ", from: 102.77, to: 105.35 },
  { text: "ตัวยาว สีแดงเข้ม", from: 105.3, to: 107.23 },
  { text: "ขานับไม่ถ้วน", from: 107.18, to: 108.5 },
  { text: "มันคลานช้าๆ ตรงไปที่เปล", from: 108.45, to: 111.2 },
  { text: "ตอนต่อไป · ร้อยขา", from: 112.36, to: 116.26 },
];

export const GECKO_LEGEND_EP03: Episode = {
  voiceoverSrc: `${DIR}/vo.mp3`,
  musicSrc: `${DIR}/music.mp3`,
  musicVolume: 0.22,
  shots: SHOTS,
  captions: CAPTIONS,
  timestampShots: [],
  timestampLabel: "",
  captionStyle: "legend",
  cleanLook: true,
};
