/**
 * "สงครามเรือนสัก" ตอนที่ 2 — ทัพกินเร็ว.
 *
 * The young soldiers return with three hundred followers and argue the red-stickered pillar
 * should be eaten before it is felled. Old Broken-Fang forbids it; the tribe splits, the
 * pillar is gnawed hollow, and the old woman knocks twice for the first time in ninety generations.
 *
 * Every shot is a Kling 2.5 clip whose first frame is the still in `src`.
 * Generated by projects/termite-war/ep02/build_ep2.py — edit there.
 */

import type { Caption, Episode, Shot } from "../roachwar/constants";

const DIR = "termite/ep02";
const clip = (n: string) => `${DIR}/video/${n}.mp4`;
const still = (n: string) => `${DIR}/${n}.png`;

const shot = (
  id: string,
  n: string,
  from: number,
  to: number,
  extra: Partial<Shot> = {},
): Shot => ({
  id,
  src: still(n),
  video: clip(n),
  durationInSeconds: Number((to - from).toFixed(3)),
  zoom: [1.0, 1.0],
  ...extra,
});

const SHOTS: Shot[] = [
  shot("peace", "s01", 0.0, 5.45),
  shot("the-return", "s02", 5.45, 7.95),
  shot("three-hundred", "s03", 7.95, 10.96),
  shot("before-the-pillar", "s04", 10.96, 19.46),
  shot("the-argument", "s05", 19.46, 27.45),
  shot("the-borer", "s06", 27.45, 35.94),
  shot("the-general", "s07", 35.94, 39.97),
  shot("the-warning", "s08", 39.97, 45.48),
  shot("the-standoff", "s09", 45.48, 53.46),
  shot("no-answer", "s10", 53.46, 55.47),
  shot("the-split", "s11", 55.47, 61.96),
  shot("the-gnawing", "s12", 61.96, 66.07),
  shot("the-pillar-cries", "s13", 66.07, 69.95),
  shot("the-vigil", "s14", 69.95, 75.96),
  shot("hollow", "s15", 75.96, 79.96),
  shot("the-feet", "s16", 79.96, 82.94),
  shot("the-hollow-knock", "s17", 82.94, 88.94),
  shot("the-two-knocks", "s18", 88.94, 98.97),
  shot("eyes-closed", "s19", 98.97, 106.11),
  shot("the-end", "s19e", 106.11, 111.61, { video: undefined, zoom: [1.0, 1.08] }),
];

const CAPTIONS: Caption[] = [
  { text: "ข้าไม่เคยเห็นปลวกทะเลาะกันมาก่อน", from: 0, to: 2.05 },
  { text: "เก้าสิบรุ่นเรามีแต่คนที่ขุด", from: 2.0, to: 4.57 },
  { text: "กับคนที่กิน", from: 4.52, to: 5.55 },
  { text: "จนคืนที่ทหารหนุ่มสองตนกลับมา", from: 5.5, to: 8.05 },
  { text: "พร้อมปลวกอีกสามร้อยตัว", from: 8.0, to: 9.75 },
  { text: "ที่ไม่ยอมฟังใคร", from: 9.7, to: 11.06 },
  { text: "พวกเขามายืนหน้าเสาต้นข้างครัว", from: 11.01, to: 14.06 },
  { text: "แล้วบอกทุกตัวว่า", from: 14.01, to: 15.52 },
  { text: "แผ่นสีแดงคือใบสั่งตาย", from: 15.47, to: 17.56 },
  { text: "เสาต้นนั้นจะถูกโค่นแน่", from: 17.51, to: 19.56 },
  { text: "ถ้ามันจะหายไปอยู่แล้ว", from: 19.51, to: 21.54 },
  { text: "ทำไมต้องปล่อยให้ไม้เน่าไปเปล่า ๆ", from: 21.49, to: 23.55 },
  { text: "กินมันตอนนี้", from: 23.5, to: 24.58 },
  { text: "ลูกของราชินีจะแข็งแรงพอจะหนีทัน", from: 24.53, to: 27.55 },
  { text: "ข้าแอบเห็นด้วย", from: 27.5, to: 28.68 },
  { text: "และนั่นคือสิ่งที่ข้ากลัวที่สุด", from: 28.63, to: 31.05 },
  { text: "ข้ารู้ว่าถ้าทั้งเผ่ากินพร้อมกัน", from: 31.0, to: 33.05 },
  { text: "เสาต้นนั้นจะไม่เหลือ", from: 33.0, to: 34.57 },
  { text: "ภายในสามคืน", from: 34.52, to: 36.04 },
  { text: "ท่านเขี้ยวหักออกมาจากโพรงราชินี", from: 35.99, to: 38.56 },
  { text: "ท่านพูดเบา ๆ ว่า", from: 38.51, to: 40.07 },
  { text: "เสาที่ยังแบกหลังคา", from: 40.02, to: 42.04 },
  { text: "ไม่ใช่ไม้ที่ตายแล้ว", from: 41.99, to: 43.05 },
  { text: "ใครแตะมัน", from: 43.0, to: 43.89 },
  { text: "ข้าจะเป็นคนหยุดเอง", from: 43.84, to: 45.58 },
  { text: "ทหารหนุ่มถามว่า", from: 45.53, to: 47.55 },
  { text: "ท่านหยุดพวกเราได้กี่ตัว", from: 47.5, to: 49.55 },
  { text: "ท่านปกป้องเสามาทั้งชีวิต", from: 49.5, to: 51.54 },
  { text: "แต่เสาเคยปกป้องท่านกลับบ้างไหม", from: 51.49, to: 53.56 },
  { text: "ท่านเขี้ยวหักไม่ตอบ", from: 53.51, to: 55.57 },
  { text: "คืนนั้นเผ่าก็แตกเป็นสองฝั่ง", from: 55.52, to: 58.04 },
  { text: "ส่วนข้ายืนอยู่กลางอุโมงค์", from: 57.99, to: 59.83 },
  { text: "เส้นเดียว", from: 59.78, to: 60.54 },
  { text: "ที่ต่อสองฝั่งเข้าด้วยกัน", from: 60.49, to: 62.06 },
  { text: "แล้วเสียงกัดก็เริ่มขึ้น", from: 62.01, to: 64.07 },
  { text: "สามร้อยตัวพร้อมกัน", from: 64.02, to: 66.17 },
  { text: "ข้าเอามือแนบผนัง", from: 66.12, to: 67.56 },
  { text: "แล้วรู้สึกว่าเสาร้องออกมา", from: 67.51, to: 70.05 },
  { text: "ท่านเขี้ยวหักไม่กินไม่นอน", from: 70.0, to: 72.06 },
  { text: "นั่งเฝ้าหน้าโพรงราชินี", from: 72.01, to: 74.08 },
  { text: "ส่วนสามคืนต่อมา", from: 74.03, to: 76.06 },
  { text: "เสาข้างครัวโปร่ง", from: 76.01, to: 77.56 },
  { text: "จนแสงไฟของครัวลอดลงมาได้", from: 77.51, to: 80.06 },
  { text: "เช้าวันที่สี่ ยายลงมาใต้ถุน", from: 80.01, to: 83.04 },
  { text: "เธอเอาข้อนิ้วก๊อกที่เสาข้างครัว", from: 82.99, to: 85.04 },
  { text: "แล้วเสียงมันก้องกลวงเหมือนกลอง", from: 84.99, to: 87.07 },
  { text: "เธอนิ่งไปนานมาก", from: 87.02, to: 89.04 },
  { text: "แล้วเธอเดินไปที่เสาต้นกลาง", from: 88.99, to: 91.1 },
  { text: "ก๊อกหนึ่งที", from: 91.05, to: 92.7 },
  { text: "รอ", from: 92.65, to: 93.08 },
  { text: "แล้วก๊อกอีกที", from: 93.03, to: 95.05 },
  { text: "เป็นครั้งแรกในเก้าสิบรุ่น", from: 95.0, to: 97.08 },
  { text: "ที่ยายก๊อกสองครั้ง", from: 97.03, to: 99.07 },
  { text: "ท่านเขี้ยวหักหลับตา", from: 99.02, to: 101.04 },
  { text: "แล้วพูดว่า", from: 100.99, to: 101.71 },
  { text: "นั่นไม่ใช่เสียงทักทาย", from: 101.66, to: 103.06 },
  { text: "นั่นคือเสียงของคนที่กำลังนับ", from: 103.01, to: 106.46 },
  { text: "ตอนต่อไป · ฝนพิษ", from: 106.91, to: 111.31 },
];

export const TERMITE_EP02: Episode = {
  voiceoverSrc: `${DIR}/vo.mp3`,
  musicSrc: `${DIR}/music.mp3`,
  musicVolume: 0.22,
  shots: SHOTS,
  captions: CAPTIONS,
  timestampShots: [],
  timestampLabel: "",
  captionStyle: "legend",
  cleanLook: true,
};
