/**
 * "สงครามเรือนสัก" ตอนที่ 3 — ฝนพิษ.
 *
 * The house is sprayed. The old guard seal the tunnels with mud and their own bodies, the
 * young soldiers flee the hollowed pillar, and Old Broken-Fang plugs the last tunnel to the
 * queen with his head. The old woman lays her palm on the pillar again, and her hand shakes.
 *
 * Every shot is a Kling 2.5 clip whose first frame is the still in `src`.
 * Generated by projects/termite-war/ep03/build_ep3.py — edit there.
 */

import type { Caption, Episode, Shot } from "../roachwar/constants";

const DIR = "termite/ep03";
const clip = (n: string) => `${DIR}/video/${n}.mp4`;
const still = (n: string) => `${DIR}/${n}.png`;

const shot = (
  id: string,
  n: string,
  from: number,
  to: number,
  extra: Partial<Shot> = {},
): Shot => ({
  id,
  src: still(n),
  video: clip(n),
  durationInSeconds: Number((to - from).toFixed(3)),
  zoom: [1.0, 1.0],
  ...extra,
});

const SHOTS: Shot[] = [
  shot("the-smell", "s01", 0.0, 1.86),
  shot("sniffing", "s02", 1.86, 7.88),
  shot("the-general-rises", "s03", 7.88, 12.25),
  shot("the-order", "s04", 12.25, 18.61),
  shot("old-guard", "s05", 18.61, 23.68),
  shot("sealing", "s06", 23.68, 28.66),
  shot("the-borer-runs", "s07", 28.66, 36.17),
  shot("the-rain-begins", "s08", 36.17, 40.42),
  shot("the-first-fall", "s09", 40.42, 45.81),
  shot("hollow-pillar", "s10", 45.81, 50.77),
  shot("the-flight", "s11", 50.77, 56.13),
  shot("last-tunnel", "s12", 56.13, 62.97),
  shot("alone", "s13", 62.97, 65.56),
  shot("the-plug", "s14", 65.56, 71.7),
  shot("last-words", "s15", 71.7, 76.41),
  shot("evening", "s16", 76.41, 79.61),
  shot("the-kneeling", "s17", 79.61, 85.83),
  shot("the-hand", "s18", 85.83, 91.98),
  shot("the-tremor", "s19", 91.98, 95.25),
  shot("the-end", "s18e", 95.25, 100.75, { video: undefined, zoom: [1.0, 1.08] }),
];

const CAPTIONS: Caption[] = [
  { text: "สามวันหลังยายก๊อกสองที", from: 0.0, to: 1.96 },
  { text: "ข้าได้กลิ่น", from: 1.91, to: 2.51 },
  { text: "ที่ไม่เคยได้กลิ่นมาก่อน", from: 2.46, to: 3.94 },
  { text: "ฉุนแล้วก็หวาน", from: 3.89, to: 5.29 },
  { text: "ลอยลงมาจากช่องพื้นห้องครัว", from: 5.24, to: 7.98 },
  { text: "ท่านเขี้ยวหักรู้ทันที", from: 7.93, to: 9.96 },
  { text: "ท่านลุกขึ้นทั้งที่ตัวผอม", from: 9.91, to: 11.55 },
  { text: "จนเขี้ยวสั่น", from: 11.5, to: 12.35 },
  { text: "แล้วสั่งเสียงดังเป็นครั้งแรก", from: 12.3, to: 14.28 },
  { text: "ว่าฝนพิษมาแล้ว", from: 14.23, to: 15.81 },
  { text: "ปิดอุโมงค์ทุกเส้นที่ลงไปหาราชินี", from: 15.76, to: 18.71 },
  { text: "ทหารเฒ่าสิบกว่าตัว", from: 18.66, to: 20.26 },
  { text: "ที่เฝ้าโพรงมาทั้งชีวิต", from: 20.21, to: 21.97 },
  { text: "ไม่มีใครถามสักคำ", from: 21.92, to: 23.78 },
  { text: "พวกเขาเดินเข้าอุโมงค์", from: 23.73, to: 25.22 },
  { text: "แล้วเอาโคลนกับตัวเอง", from: 25.17, to: 26.65 },
  { text: "อุดปากทางทีละเส้น", from: 26.6, to: 28.76 },
  { text: "ส่วนข้ารู้จักทุกอุโมงค์", from: 28.71, to: 30.78 },
  { text: "ข้าวิ่งไปทั่วเสา", from: 30.73, to: 32.1 },
  { text: "เอามือแนบผนังทีละจุด", from: 32.05, to: 33.59 },
  { text: "ตะโกนบอกว่าลมจะพัดเข้าทางไหน", from: 33.54, to: 36.27 },
  { text: "แล้วฝนก็ตก", from: 36.22, to: 37.09 },
  { text: "ละอองสีขาวพุ่งเข้ามา", from: 37.04, to: 38.74 },
  { text: "ตามรูเล็ก ๆ บนผนัง", from: 38.69, to: 40.52 },
  { text: "ตัวที่โดนก่อนไม่ได้ร้อง", from: 40.47, to: 42.45 },
  { text: "มันแค่หยุดเดิน", from: 42.4, to: 44.13 },
  { text: "แล้วค่อย ๆ เอนลง", from: 44.08, to: 45.91 },
  { text: "เสาข้างครัว", from: 45.86, to: 46.77 },
  { text: "ที่พวกทหารหนุ่มกินจนโปร่ง", from: 46.72, to: 48.88 },
  { text: "ไม่มีอะไรกั้นละอองเลย", from: 48.83, to: 50.87 },
  { text: "พวกเขาวิ่งหนีมาที่เสาต้นกลาง", from: 50.82, to: 53.16 },
  { text: "หน้าที่เคยดุ", from: 53.11, to: 54.45 },
  { text: "เหลือแต่ความกลัว", from: 54.4, to: 56.23 },
  { text: "เหลืออุโมงค์เส้นสุดท้าย", from: 56.18, to: 58.24 },
  { text: "เส้นที่ต่อลงไปถึงโพรงราชินี", from: 58.19, to: 60.91 },
  { text: "ทหารเฒ่าไม่เหลือใครแล้ว", from: 60.86, to: 63.07 },
  { text: "ท่านเขี้ยวหักเดินเข้าไปคนเดียว", from: 63.02, to: 65.66 },
  { text: "ท่านเอาหัวอุดปากอุโมงค์", from: 65.61, to: 67.14 },
  { text: "เหมือนที่เคยอุดรอยรั่วตอนน้ำท่วม", from: 67.09, to: 69.67 },
  { text: "เขี้ยวข้างที่หักกดลงบนโคลน", from: 69.62, to: 71.8 },
  { text: "ท่านบอกข้าเบา ๆ ว่า", from: 71.75, to: 73.45 },
  { text: "บอกนางด้วย", from: 73.4, to: 74.51 },
  { text: "ว่าบ้านยังมีคนดูแล", from: 74.46, to: 76.51 },
  { text: "ฝนหยุดตอนเย็น", from: 76.46, to: 77.65 },
  { text: "ทหารหนุ่มที่เคยถามว่า", from: 77.6, to: 79.71 },
  { text: "ท่านหยุดพวกเราได้กี่ตัว", from: 79.66, to: 81.67 },
  { text: "คุกเข่าอยู่หน้าอุโมงค์", from: 81.62, to: 83.28 },
  { text: "ที่ถูกอุดไว้", from: 83.23, to: 84.24 },
  { text: "เขาไม่พูดอะไรเลย", from: 84.19, to: 85.93 },
  { text: "คืนนั้นยายลงมาใต้ถุน", from: 85.88, to: 88.26 },
  { text: "วางฝ่ามือบนเสาต้นกลางอีกครั้ง", from: 88.21, to: 90.67 },
  { text: "ความอุ่นเท่าเดิม", from: 90.62, to: 92.08 },
  { text: "แต่คราวนี้ข้ารู้สึกได้", from: 92.03, to: 93.8 },
  { text: "ว่ามือของเธอสั่น", from: 93.75, to: 95.61 },
  { text: "ตอนต่อไป · เครื่องจักรใหญ่", from: 96.05, to: 100.45 },
];

export const TERMITE_EP03: Episode = {
  voiceoverSrc: `${DIR}/vo.mp3`,
  musicSrc: `${DIR}/music.mp3`,
  musicVolume: 0.22,
  shots: SHOTS,
  captions: CAPTIONS,
  timestampShots: [],
  timestampLabel: "",
  captionStyle: "legend",
  cleanLook: true,
};
