/**
 * "สงครามเจ้าพระยา" ตอนที่ 1 — มานาหยุดตก.
 *
 * Told by an old iridescent shark catfish of the temple-pier sanctuary on the
 * Chao Phraya. The catfish, fat on the bread tourists throw, have forgotten
 * how to fight; blackchin tilapia ride the salt tide upstream, eat the egg
 * beds and steal the manna. The narrator catches one, finds its mouth full of
 * young, and lets it go.
 *
 * Every shot is a Kling 2.5 clip whose first frame is the still in `src`.
 * Generated by projects/chao-phraya-war/ep01/build_ep1.py — edit there.
 */

import type { Caption, Episode, Shot } from "../roachwar/constants";

const DIR = "chaophraya/ep01";
const clip = (n: string) => `${DIR}/video/${n}.mp4`;
const still = (n: string) => `${DIR}/${n}.png`;

const shot = (
  id: string,
  n: string,
  from: number,
  to: number,
  extra: Partial<Shot> = {},
): Shot => ({
  id,
  src: still(n),
  video: clip(n),
  durationInSeconds: Number((to - from).toFixed(3)),
  zoom: [1.0, 1.0],
  ...extra,
});

const SHOTS: Shot[] = [
  shot("battle-hook", "s01", 0.0, 5.71),
  shot("the-pier", "s02", 5.71, 9.63),
  shot("never-hunted", "s03", 9.63, 13.15),
  shot("the-hand", "s04", 13.15, 15.64),
  shot("manna", "s05", 15.64, 19.72),
  shot("the-kingdom", "s06", 19.72, 24.82),
  shot("sleeping-army", "s07", 24.82, 28.4),
  shot("forever", "s08", 28.4, 33.13),
  shot("the-flood", "s09", 33.13, 35.37),
  shot("salt-tide", "s10", 35.37, 40.5),
  shot("smaller-than-my-fin", "s11", 40.5, 43.84),
  shot("the-swarm", "s12", 43.84, 48.04),
  shot("eggs-devoured", "s13", 48.04, 51.65),
  shot("empty-sand", "s14", 51.65, 56.13),
  shot("the-council", "s15", 56.13, 62.58),
  shot("stolen-manna", "s16", 62.58, 69.09),
  shot("the-phone", "s17", 69.09, 71.61),
  shot("pushed-aside", "s18", 71.61, 73.47),
  shot("the-wreck", "s19", 73.47, 76.8),
  shot("white-whiskers", "s20", 76.8, 79.47),
  shot("teeth", "s21", 79.47, 84.12),
  shot("the-captive", "s22", 84.12, 90.34),
  shot("the-mouth", "s23", 90.34, 93.0),
  shot("mercy", "s24", 93.0, 96.11),
  shot("release", "s25", 96.11, 97.99),
  shot("the-young-feed", "s26", 97.99, 101.11),
  shot("defeated", "s27", 101.11, 106.42),
  shot("upstream", "s28", 106.42, 111.42),
];

const CAPTIONS: Caption[] = [
  { text: "ทุกสงคราม", from: 0, to: 0.81 },
  { text: "ไม่ได้เริ่มจากความหิว", from: 0.76, to: 2.34 },
  { text: "แต่เริ่มจากความอิ่ม", from: 2.29, to: 3.71 },
  { text: "ที่อิ่มนานเกินไป", from: 3.66, to: 5.42 },
  { text: "ข้าเกิดใต้ท่าน้ำวัด", from: 5.76, to: 7.25 },
  { text: "ในแม่น้ำที่ยักษ์เรียกว่าเจ้าพระยา", from: 7.2, to: 9.73 },
  { text: "ตลอดชีวิตวัยเยาว์", from: 9.68, to: 11.22 },
  { text: "ข้าไม่เคยต้องล่าอะไรเลย", from: 11.17, to: 13.16 },
  { text: "ทุกเช้า", from: 13.2, to: 13.87 },
  { text: "ยักษ์จะเดินลงมาที่ท่าน้ำ", from: 13.82, to: 15.74 },
  { text: "แล้วโปรยขนมปังลงมาจากฟ้า", from: 15.69, to: 17.76 },
  { text: "เผ่าของเราเรียกมันว่ามานา", from: 17.71, to: 19.82 },
  { text: "และเรียกผืนน้ำหน้าวัดว่าเขตอภัยทาน", from: 19.77, to: 22.91 },
  { text: "ที่ไม่มีใครกล้าล่าเรา", from: 22.86, to: 24.83 },
  { text: "ฟันของพวกเรา", from: 24.87, to: 26.12 },
  { text: "ทื่อไปหมดแล้ว", from: 26.07, to: 27.03 },
  { text: "นักรบของเราไม่เคยรบ", from: 26.98, to: 28.5 },
  { text: "เราตัวใหญ่", from: 28.45, to: 29.43 },
  { text: "เราอ้วน", from: 29.38, to: 30.12 },
  { text: "และเราเชื่อว่าโลกจะเป็นอย่างนี้ตลอดไป", from: 30.07, to: 32.85 },
  { text: "แล้วฤดูน้ำหลากปีนั้นก็มาถึง", from: 33.18, to: 35.47 },
  { text: "น้ำเค็มจากปากอ่าว", from: 35.42, to: 36.83 },
  { text: "ดันขึ้นมาไกลกว่าทุกปี", from: 36.78, to: 38.57 },
  { text: "และพาพวกมันมาด้วย", from: 38.52, to: 40.52 },
  { text: "พวกมันตัวเล็กกว่าครีบของข้า", from: 40.55, to: 42.39 },
  { text: "คางดำเหมือนเขม่าไฟ", from: 42.34, to: 43.94 },
  { text: "ตัวเดียวไม่มีความหมายอะไรเลย", from: 43.89, to: 45.65 },
  { text: "แต่พวกมันไม่เคยมาตัวเดียว", from: 45.6, to: 47.94 },
  { text: "คืนแรก", from: 48.09, to: 48.92 },
  { text: "แหล่งไข่ทางเหนือของท่าน้ำ", from: 48.87, to: 50.7 },
  { text: "หายไปทั้งแหล่ง", from: 50.65, to: 51.75 },
  { text: "คืนที่สอง", from: 51.7, to: 52.66 },
  { text: "ทางใต้", from: 52.61, to: 53.49 },
  { text: "เราตื่นมา", from: 53.44, to: 54.54 },
  { text: "พบแค่ทรายเปล่า", from: 54.49, to: 56.03 },
  { text: "สภาผู้เฒ่าบอกว่าไม่ต้องกลัว", from: 56.18, to: 58.24 },
  { text: "ยักษ์จะปกป้องเขตอภัยทาน", from: 58.19, to: 60.34 },
  { text: "เหมือนที่เคยปกป้องมาเสมอ", from: 60.29, to: 62.39 },
  { text: "แต่เช้าวันนั้น", from: 62.63, to: 63.76 },
  { text: "ยักษ์โปรยมานาลงมาเหมือนทุกวัน", from: 63.71, to: 65.83 },
  { text: "และทะเลสีดำก็พุ่งขึ้นมา", from: 65.78, to: 67.63 },
  { text: "แย่งกินก่อนเราทั้งหมด", from: 67.58, to: 69.19 },
  { text: "ยักษ์หัวเราะ", from: 69.14, to: 70.17 },
  { text: "ยกโทรศัพท์ขึ้นถ่ายรูป", from: 70.12, to: 71.71 },
  { text: "แล้วโยนเพิ่ม", from: 71.66, to: 73.27 },
  { text: "ข้าไปหาแม่ทัพชรา", from: 73.52, to: 74.94 },
  { text: "ผู้เดียวที่ยังจำวิธีรบได้", from: 74.89, to: 76.9 },
  { text: "ท่านหนวดขาวมองข้าอยู่นาน", from: 76.85, to: 78.62 },
  { text: "แล้วพูดว่า", from: 78.57, to: 79.57 },
  { text: "เผ่าที่ไม่เคยหิว", from: 79.52, to: 81.02 },
  { text: "ลืมไปแล้วว่าฟันมีไว้ทำอะไร", from: 80.97, to: 83.8 },
  { text: "คืนนั้น", from: 84.17, to: 85.04 },
  { text: "ข้าจับคางดำได้ตัวหนึ่ง", from: 84.99, to: 86.57 },
  { text: "ปากของมันปิดแน่น", from: 86.52, to: 87.88 },
  { text: "ข้ากดมันไว้กับโคลน", from: 87.83, to: 89.35 },
  { text: "จนมันยอมอ้าปาก", from: 89.3, to: 90.44 },
  { text: "ในปากของมัน", from: 90.39, to: 91.49 },
  { text: "มีลูกเล็กๆ นับร้อย", from: 91.44, to: 93.1 },
  { text: "มันไม่ได้ซ่อนอาวุธ", from: 93.05, to: 94.12 },
  { text: "มันกำลังอุ้มลูก", from: 94.07, to: 95.8 },
  { text: "ข้าปล่อยมันไป", from: 96.16, to: 97.19 },
  { text: "คืนต่อมา", from: 97.14, to: 98.09 },
  { text: "ลูกนับร้อยตัวนั้น", from: 98.04, to: 99.19 },
  { text: "ก็กินไข่ของเราไปอีกแหล่ง", from: 99.14, to: 101.21 },
  { text: "นั่นคือสงครามครั้งแรกที่ข้าแพ้", from: 101.16, to: 103.39 },
  { text: "และข้าแพ้", from: 103.34, to: 104.12 },
  { text: "เพราะความเมตตา", from: 104.07, to: 106.07 },
  { text: "ตอนต่อไป · ทัพปากแม่น้ำ", from: 107.22, to: 111.12 },
];

export const CHAO_PHRAYA_EP01: Episode = {
  voiceoverSrc: `${DIR}/vo.mp3`,
  musicSrc: `${DIR}/music.mp3`,
  musicVolume: 0.22,
  shots: SHOTS,
  captions: CAPTIONS,
  timestampShots: [],
  timestampLabel: "",
  captionStyle: "legend",
  cleanLook: true,
};
